name: Run Cypress Tests on Multiple Browsers

on: [push]

jobs:
  cypress-chrome:
    runs-on: ubuntu-latest
    name: Cypress Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress on Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: false
          config-file: cypress.config.js
          config: video=false,screenshot=on-failure

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos
          if-no-files-found: ignore

  cypress-firefox:
    runs-on: ubuntu-latest
    name: Cypress Firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress on Firefox
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          record: false
          config-file: cypress.config.js
          config: video=false,screenshot=on-failure

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-firefox
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-firefox
          path: cypress/videos
          if-no-files-found: ignore

  generate-report:
    runs-on: ubuntu-latest
    needs: [cypress-chrome, cypress-firefox]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install mochawesome reporter
        run: npm install --save-dev mochawesome mochawesome-merge mochawesome-report-generator

      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          path: cypress/results

      - name: Generate HTML report
        run: |
          npx mochawesome-merge cypress/results/*.json > cypress/results/output.json
          npx marge cypress/results/output.json --reportDir cypress/reports --inline

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-report
          path: cypress/reports
          if-no-files-found: ignore

  send-email-report:
    runs-on: ubuntu-latest
    needs: [generate-report]
    if: always()
    steps:
      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: cypress-test-report
          path: cypress/reports

      - name: Send email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Cypress Test Results - ${{ github.event.head_commit.message }}"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Cypress test results for commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            Commit message: ${{ github.event.head_commit.message }}
            
            Test results are attached.
            
            View the full report: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          attachments: cypress/reports/mochawesome.html

    